apiVersion: v1
kind: ConfigMap
metadata:
  name: speedtest-tracker-config
data:
  PUID: "1000"  # User ID for file permissions
  PGID: "1000"  # Group ID for file permissions
  TZ: "Etc/UTC"  # Set the timezone
  APP_KEY: ""  # Application key for security; leave blank if not required
  APP_URL: ""  # Publicly accessible URL of the application; leave blank if not set
  DB_CONNECTION: "sqlite"  # Set the database type to use:
                           # "sqlite" for lightweight embedded databases (default)
                           # "pgsql" for PostgreSQL (requires external setup)
                           # "mysql" for MySQL (requires external setup)
  SPEEDTEST_SCHEDULE: ""  # Cron-style schedule for speed tests; leave blank for manual runs
  SPEEDTEST_SERVERS: ""  # Specify server IDs for targeted tests; leave blank for auto-selection
  DISPLAY_TIMEZONE: "Etc/UTC"  # Timezone for displaying test results
  PRUNE_RESULTS_OLDER_THAN: "0"  # Automatically prune results older than specified days; "0" disables pruning
