apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker
  labels:
    app: speedtest-tracker
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: speedtest-tracker
  type: ClusterIP
